const ERROR_CODE_NOT_FOUND = 404;
const ERROR_CODE_NO_AUTHORIZATION = 401;
const VALIDATION_ERROR_MESSAGE = 'Ошибка валидации.';
const INTERNAL_SERVER_ERROR_MESSAGE = 'На сервере произошла ошибка.';
const INVALID_ID_ERROR_MESSAGE = 'Невалидный id.';
const CARD_NOT_FOUND_ERROR_MESSAGE = 'Нет карточки с таким id.';
const USER_NOT_FOUND_ERROR_MESSAGE = 'Нет пользователя с таким id.';
const NO_AUTHORIZATION_ERROR_MESSAGE = 'У Вас нет прав удалять данную карточку!';

module.exports = {
  ERROR_CODE_NOT_FOUND,
  VALIDATION_ERROR_MESSAGE,
  INTERNAL_SERVER_ERROR_MESSAGE,
  INVALID_ID_ERROR_MESSAGE,
  CARD_NOT_FOUND_ERROR_MESSAGE,
  USER_NOT_FOUND_ERROR_MESSAGE,
  NO_AUTHORIZATION_ERROR_MESSAGE,
  ERROR_CODE_NO_AUTHORIZATION,
};
