const ERROR_CODE_BAD_REQUEST = 400;
const ERROR_CODE_ISE = 500;
const ERROR_CODE_NOT_FOUND = 404;
const VALIDATION_ERROR_MESSAGE = 'Ошибка валидации.';
const INTERNAL_SERVER_ERROR_MESSAGE = 'На сервере произошла ошибка.';
const INVALID_ID_ERROR_MESSAGE = 'Невалидный id.';
const CARD_NOT_FOUND_ERROR_MESSAGE = 'Нет карточки с таким id.';
const USER_NOT_FOUND_ERROR_MESSAGE = 'Нет пользователя с таким id.';

module.exports = {
  ERROR_CODE_BAD_REQUEST,
  ERROR_CODE_ISE,
  ERROR_CODE_NOT_FOUND,
  VALIDATION_ERROR_MESSAGE,
  INTERNAL_SERVER_ERROR_MESSAGE,
  INVALID_ID_ERROR_MESSAGE,
  CARD_NOT_FOUND_ERROR_MESSAGE,
  USER_NOT_FOUND_ERROR_MESSAGE,
};
